### ISSUE TITLE
Sidebar in the Docs site resets its scroll position to the top upon clicking a link in it

### ISSUE THREAD

**Issue by ADTC** [lavrton/polotno-site#44]
See video. It's quite annoying, as you have to scroll down again if you're trying to see different pages in the same section.

https://github.com/user-attachments/assets/a618c0c4-4adf-4e85-9946-7c64d1749997

**Comment by lavrton** [comment]
Oh, that is an excellent feedback. Thanks for it. Just made an update to improve it. Please let me know how it works for you.

@ADTC thanks a lot of all of other feedback.

**Comment by ADTC** [comment]
Thank you. It works much better now.

**Comment by ADTC** [comment]
Although, on mobile site, the sidebar seems to be completely hidden, and there's no way to access it. I thought there could be a menu icon which will reveal it but there was none.
