### ISSUE TITLE
Suggestion: Link to this GitHub project in the Docs site

### ISSUE THREAD

**Issue by ADTC** [lavrton/polotno-site#45]
I suggest adding a link to this GitHub project in the docs site so you can get more issues and pull requests to fix/improve the docs. 🙂

Best if each page can have a contextual link at the bottom to directly edit it in GitHub (by opening a PR). See mockup:

<img width="1444" alt="image" src="https://github.com/user-attachments/assets/5ab93963-322a-427b-8d15-b319dc74985e">

But a simple link to the project will also do.

---

_BTW:_ I found that none of the GitHub projects under `polotno-project` are linked anywhere in `polotno.com` so I could only find these projects through a Google search. (Though I found the [Roadmap & bug reports](https://github.com/orgs/polotno-project/projects/1/views/1) link in the footer later on.)

**Comment by lavrton** [comment]
Thanks for the suggestion. Some time ago I migrated the side from this GitHub repo, to framer platform. I hope one day I will be able to find a way to edit docs again from the GitHub.
